name: iyam_core
description: Core foundation package (network, storage, utils)
version: 0.1.2
homepage: https://github.com/iyamdev/iyam_core
repository: https://github.com/iyamdev/iyam_core

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0
  image_picker: ^1.2.1
