name: iyam_core
description: Core foundation package (network, storage, utils)
version: 0.2.1
homepage: https://github.com/iyamdev/iyam_core
repository: https://github.com/iyamdev/iyam_core

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  image_picker: ^1.2.1
